### ISSUE TITLE
Breaks with GCC 6

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaOptimizers/AmplNLReader.jl#16]
See ampl/mp#85.

Would require changing to ~~https://github.com/gidden/mp, which has the fix, but not the release 2.1.1, or to~~ 3.1.0.

**Comment by dpo** [comment]
Are you saying that upgrading to 3.1.0 would resolve the issue?

**Comment by abelsiqueira** [comment]
Yes, I installed on my machine locally, and it works.
Also, I tried using 2.1.1, but the tests fails, so only 3.1.0, AFAIK.

**Comment by dpo** [comment]
Closed by #17.
