### ISSUE TITLE
obj_weight change to sigma

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaOptimizers/AmplNLReader.jl#22]
@dpo @mlubin 
Due to changes on NLPModels, I'm changing `obj_weight` to `\sigma`.
I'll make a PR to fix this on `AmplMathProgInterface.jl`. Is there anywhere else
that will break?

**Comment by dpo** [comment]
I have to say I like `obj_weight` much better than `sigma`.

**Comment by abelsiqueira** [comment]
Then I'll close the PRs and use `obj_weight` instead.
